Install and uninstall scripts fixed to work on Linux

diff --git a/run/install b/run/install
--- a/run/install
+++ b/run/install
@@ -8,5 +8,9 @@ fi
 
 cd $(dirname "$0")
 ln -s $(pwd)/hog $target_link
+if [ $? -ne 0 ]; then
+  echo "Failed to create symbolic link; existing."
+  exit 1
+fi
 
 echo "Installed to $target_link"
diff --git a/run/uninstall b/run/uninstall
--- a/run/uninstall
+++ b/run/uninstall
@@ -3,6 +3,10 @@
 target_link=/usr/local/bin/hog
 if [ -L $target_link ]; then
   rm $target_link
+  if [ $? -ne 0 ]; then
+    echo "Failed to remove symbolic link; exiting."
+    exit 1
+  fi
 else
   echo "No symbolic $target_link found; skipping."
 fi
